### ISSUE TITLE
Test App for dinamic Views creation / destruction

### ISSUE THREAD

**Issue by zerjillo** [torresj/indi-android-ui#1]
Since the library will construct all UI based on dinamic data received from INDI servers an example Android application in which the interface is created dinamically should be developed to learn how to do it properly. This App can also be used to test how the interface is recreated when the App gets into the foreground.

**Comment by torresj** [comment]
Test done with android app Indi test https://github.com/torresj/indi-android-ui/tree/master/Android%20Test%20APP/Indi%20test
