### ISSUE TITLE
First Graphical Views design for devices / properties / elements

### ISSUE THREAD

**Issue by zerjillo** [torresj/indi-android-ui#3]
In INDI there are connections to servers, devices which are received through each connection, properties for devices and elements for each property. Some design of the interface views is needed before starting with the library. Classes for each kind of element / property and device should be done. This design could be based on the structure of the I4J Client UI Module.

**Comment by torresj** [comment]
It has created class structure. Each property is managed by a class that generates the corresponding view. Each connection has device represents by a INDI connection (one thread per connection)
